name: Automatically build packages

permissions:
  contents: read
  attestations: write
  artifact-metadata: write
  id-token: write

on:
  push:
    paths:
      - anda/**
    branches:
      - frawhide

  pull_request:
    paths:
      - anda/**
    branches:
      - frawhide

  merge_group:
    branches:
      - frawhide

  workflow_dispatch:
  workflow_call:

jobs:
  manifest:
    runs-on: ubuntu-latest

    outputs:
      packages: ${{ steps.packages.outputs.packages }}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0

      - name: Find changed packages
        id: packages
        shell: bash
        env:
          EVENT_NAME: ${{ github.event_name }}
          BEFORE_SHA: ${{ github.event.before }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          MERGE_BASE_SHA: ${{ github.event.merge_group.base_sha }}
        run: |
          set -euo pipefail

          case "$EVENT_NAME" in
            push)
              base="$BEFORE_SHA"
              head="$GITHUB_SHA"
              ;;

            pull_request)
              base="$BASE_SHA"
              head="$GITHUB_SHA"
              ;;

            merge_group)
              base="$MERGE_BASE_SHA"
              head="$GITHUB_SHA"
              ;;

            *)
              find anda \
                -mindepth 2 \
                -maxdepth 2 \
                -type d \
                -printf '%P\n' |
                sort -u |
                jq -R -s -c '
                  split("\n")
                  | map(select(length > 0))
                ' > packages.json

              echo "packages=$(cat packages.json)" >> "$GITHUB_OUTPUT"
              exit 0
              ;;
          esac

          echo "Comparing:"
          echo "  base: $base"
          echo "  head: $head"

          git diff \
            --name-only \
            "$base" "$head" |
            grep '^anda/' |
            cut -d/ -f2-3 |
            sort -u |
            jq -R -s -c '
              split("\n")
              | map(select(length > 0))
            ' > packages.json

          packages=$(cat packages.json)

          echo "Changed packages:"
          echo "$packages" | jq .

          echo "packages=$packages" >> "$GITHUB_OUTPUT"

  build:
    needs: manifest

    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.manifest.outputs.packages) }}

    uses: ./.github/workflows/build.yml
    secrets: inherit

    with:
      packages: ${{ matrix.package }}
