name: JSON Build
permissions:
  contents: read
  attestations: write
  artifact-metadata: write
  id-token: write
on:
  workflow_call:
    inputs:
      packages:
        description: "Packages to Build"
        required: true
        type: string
      publish:
        description: "Whether the package should be published"
        required: false
        type: boolean
        default: true
      custom_builder:
        description: "Custom Builder"
        required: false
        type: string
        default: ""
      bust_cache:
        description: "Whether to bust the cache"
        required: false
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      packages:
        description: "Packages to Build"
        required: true
        type: string
      publish:
        description: "Whether the package should be published"
        required: false
        type: boolean
        default: true

jobs:
  build:
    strategy:
      matrix:
        pkg: ${{ fromJson(inputs.packages) }}
        version: ["rawhide"]
      fail-fast: false
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/terrapkg/builder:f${{ matrix.version }}
      options: --cap-add=SYS_ADMIN --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Set up git repository
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Configure sccache
        id: sccache
        if: ${{ contains(matrix.pkg.labels.sccache, '1') }}
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          SCCACHE_GHA_VERSION: ${{ matrix.version }}-${{ matrix.pkg.arch }}-${{ matrix.pkg.pkg }}
          SCCACHE_GHA_CACHE_FROM: ${{ matrix.version }}-${{ matrix.pkg.arch }}-${{ matrix.pkg.pkg }}
        with:
          script: |
            const script = require('./.github/scripts/configure-sccache.js')
            await script({github, context, core, exec})

      - name: CI Setup Script
        if: ${{ !contains(matrix.pkg.labels, 'mock') }}
        run: |
          dir=$(dirname ${{ matrix.pkg.pkg }})
          if [ -f $dir/ci_setup.rhai ]; then
            anda run $dir/ci_setup.rhai --labels script_path=$dir/ci_setup.rhai
          fi

      - name: Install Build Dependencies
        if: ${{ matrix.pkg.labels.mock != '1' }}
        run: |
          dir=$(dirname ${{ matrix.pkg.pkg }})
          dnf5 in -y python3-{copr,libdnf5,rpm} dnf5-plugins

      - name: Build with Andaman
        run: anda build ${{ matrix.pkg.pkg }} -r rpmbuild -A='-bs'

      - name: Report Cache Summary
        if: steps.sccache.outcome == 'success'
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const script = require('./.github/scripts/sccache-stats.js')
            await script({github, context, core, exec})

      - name: Generating artifact name
        id: art
        run: |
          NAME=${{ matrix.pkg.pkg }}-${{ matrix.pkg.arch }}-${{ matrix.version }}
          x=${NAME//\//@}
          echo "name=$x" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ steps.art.outputs.name }}
          compression-level: 0 
          path: |
            anda-build/rpm/srpm/*

      - name: Attest build provenance
        if: inputs.publish
        uses: actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8 # v4.2.2
        with:
          subject-path: |
            anda-build/rpm/srpm/*

      - name: Notify COPR (Success)
        if: inputs.publish && success()
        run: |
          dnf copr enable -y '${{secrets.OWNER}}/${{secrets.PROJECT}}'; 
          ./.github/workflows/deps.py '${{secrets.REPOID}}' anda-build/rpm/srpm/*.src.rpm --build --tree --login '${{secrets.LOGIN}}' --token '${{secrets.TOKEN}}' --owner '${{secrets.OWNER}}' --project '${{secrets.PROJECT}}'
 
      - name: Notify COPR (Failure)
        if: inputs.publish && (cancelled() || failure())
        run: echo failed to build
